###############
###  binds  ###
###############

set $mod Mod4
set $alt Mod1

### OPEN TERMINAL
bindsym $mod+Return exec $terminal

### LOCK SCREEN
bindsym $mod+p exec $lockscreen

### OPEN MENU
bindsym $alt+space exec --no-startup-id $menu

### OPEN BROWSER
bindsym $mod+b exec brave

### KILL FOCUSED WINDOW
bindsym $mod+q kill

### CHANGE FOCUS
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+ntilde focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

### MOVE FOCUS WINDOW
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down 
bindsym $mod+Shift+l move up
bindsym $mod+Shift+ntilde move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down 
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

### SPLIT SCREEN
bindsym $mod+h split h
bindsym $mod+v split v

### TOGGLE FULLSCREEN
bindsym $mod+f fullscreen toggle


### I3 CONFIG
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart

floating_modifier Mod4
bindsym Mod4+r mode "resize"

### EXIT
bindsym $mod+Escape exit
