####################################
### MONITOR AND WORKSPACE CONFIG ###
####################################

set $m1 DP-0
set $m2 HDMI-0

exec xrandr --no-startup-id xrandr --output $m1 --auto --left-of $m2

set $ws1 "1"
set $ws2 "2"

set $ws9 "9"
set $ws10 "10"

### Binding
bindsym $mod+1 workspace $ws1

bindsym $mod+2 workspace $ws2

bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

workspace $ws1 output $m1
workspace $ws2 output $m1

workspace $ws9 output $m2
workspace $ws10 output $m2
