################
### START-UP ###
################

exec --no-startup-id dex --autostart --enviroment i3
exec --no-startup-id xss-lock --transfer-sleep-lock -- i3lock --nofork
exec --no-startup-id nm-applet

exec --no-startup-id picom

exec_always --no-startup-id ~/.config/polybar/launch.sh
exec_always --no-startup-id feh --bg-scale ~/.config/feh/imgs/background.jpg

### load nvidia settings
exec nvidia-settings -l

### Docker daemon
exec systemctl start docker

