###############
### THEMING ###
###############

set $primary #e4d201
set $default #1F1F1F

### FONT
font pango:JetBrainsMono Nerd Font:14

gaps inner 14px

### BORDERS
default_border pixel 1

client.focused              $default $default $default $primary $primary
client.focused_inactive     $default $default $default $default $default
client.unfocused            $default $default $default $default $default

